package domain

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID

	SenderID   uuid.UUID
	SenderType ParticipantType

	Type    MessageType
	Content string

	CreatedAt time.Time
	UpdatedAt time.Time

	// Advanced Features
	Metadata  map[string]interface{}
	ReadBy    map[uuid.UUID]time.Time
	AIContext *AIMessageContext
}

type AIMessageContext struct {
	Intent      string  `json:"intent"`
	Confidence  float64 `json:"confidence"`
	TokenUsage  int     `json:"token_usage"`
	IsEscalated bool    `json:"is_escalated"`
}

// IsSystem checks if this is an automated message
func (m *Message) IsSystem() bool {
	return m.Type == MessageTypeSystem || m.SenderType == ParticipantTypeSystem
}

// IsFromAI checks if this message was generated by the bot
func (m *Message) IsFromAI() bool {
	return m.SenderType == ParticipantTypeAIAgent
}
