// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"hauslet/internal/modules/property/domain"
	"time"

	"github.com/google/uuid"
)

type AmenityHighlightInput struct {
	Title   string `json:"title"`
	Summary string `json:"summary"`
	Icon    string `json:"icon"`
}

type CreateListingInput struct {
	OwnerType       domain.OwnerType            `json:"ownerType"`
	Property        *CreateListingPropertyInput `json:"property"`
	Title           string                      `json:"title"`
	Description     string                      `json:"description"`
	Currency        *domain.CurrencyCode        `json:"currency,omitempty"`
	ListingType     domain.ListingType          `json:"listingType"`
	HasCalendar     *bool                       `json:"hasCalendar,omitempty"`
	ShortletDetails *ShortletDetailInput        `json:"shortletDetails,omitempty"`
	RentalDetails   *RentalDetailInput          `json:"rentalDetails,omitempty"`
	SaleDetails     *SaleDetailInput            `json:"saleDetails,omitempty"`
}

type CreateListingPropertyInput struct {
	UnitNumber         *string                   `json:"unitNumber,omitempty"`
	Address            string                    `json:"address"`
	City               string                    `json:"city"`
	State              string                    `json:"state"`
	PostalCode         *string                   `json:"postalCode,omitempty"`
	Country            domain.CountryCode        `json:"country"`
	Location           *LocationInput            `json:"location,omitempty"`
	PropertyClass      domain.PropertyClass      `json:"propertyClass"`
	PropertyType       domain.PropertyType       `json:"propertyType"`
	FurnishingType     *domain.FurnishingType    `json:"furnishingType,omitempty"`
	PropertyCondition  *domain.PropertyCondition `json:"propertyCondition,omitempty"`
	Bedrooms           *int                      `json:"bedrooms,omitempty"`
	Bathrooms          *int                      `json:"bathrooms,omitempty"`
	Toilets            *int                      `json:"toilets,omitempty"`
	HalfBathrooms      *int                      `json:"halfBathrooms,omitempty"`
	Floors             *int                      `json:"floors,omitempty"`
	Units              *int                      `json:"units,omitempty"`
	SquareMeters       *float64                  `json:"squareMeters,omitempty"`
	FloorArea          *float64                  `json:"floorArea,omitempty"`
	Amenities          []string                  `json:"amenities,omitempty"`
	FeaturesCommercial []string                  `json:"featuresCommercial,omitempty"`
}

type ListingConnection struct {
	Edges      []*ListingEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type ListingEdge struct {
	Node   *domain.Listing `json:"node"`
	Cursor string          `json:"cursor"`
}

type ListingFilterInput struct {
	OwnerID        *uuid.UUID             `json:"ownerId,omitempty"`
	PropertyID     *uuid.UUID             `json:"propertyId,omitempty"`
	OwnerTypes     []domain.OwnerType     `json:"ownerTypes,omitempty"`
	ListingTypes   []domain.ListingType   `json:"listingTypes,omitempty"`
	Statuses       []domain.ListingStatus `json:"statuses,omitempty"`
	ReviewStatuses []domain.ReviewStatus  `json:"reviewStatuses,omitempty"`
	Published      *bool                  `json:"published,omitempty"`
	HasCalendar    *bool                  `json:"hasCalendar,omitempty"`
}

type ListingWithDistance struct {
	Listing        *domain.Listing `json:"listing"`
	DistanceMeters float64         `json:"distanceMeters"`
	Score          *float64        `json:"score,omitempty"`
}

type LocationInput struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type MediaInput struct {
	Group        *string `json:"group,omitempty"`
	Caption      *string `json:"caption,omitempty"`
	IsPrimary    *bool   `json:"isPrimary,omitempty"`
	IsGroupCover *bool   `json:"isGroupCover,omitempty"`
	Order        *int    `json:"order,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RentalDetailInput struct {
	RentalPrice            float64               `json:"rentalPrice"`
	RentalPricePeriod      domain.PaymentPeriod  `json:"rentalPricePeriod"`
	AgencyFee              *float64              `json:"agencyFee,omitempty"`
	LegalFee               *float64              `json:"legalFee,omitempty"`
	RegistrationFee        *float64              `json:"registrationFee,omitempty"`
	CautionFee             *float64              `json:"cautionFee,omitempty"`
	ServiceCharge          *float64              `json:"serviceCharge,omitempty"`
	ServiceCharges         []*ServiceChargeInput `json:"serviceCharges,omitempty"`
	MinRentalPeriod        int                   `json:"minRentalPeriod"`
	MaxRentalPeriod        *int                  `json:"maxRentalPeriod,omitempty"`
	RentalAvailabilityFrom *time.Time            `json:"rentalAvailabilityFrom,omitempty"`
	RentalTerms            *string               `json:"rentalTerms,omitempty"`
	RentalRules            []*RuleGroupInput     `json:"rentalRules,omitempty"`
}

type RuleGroupInput struct {
	Category domain.RuleCategory `json:"category"`
	Rules    []string            `json:"rules"`
}

type SaleDetailInput struct {
	SalePrice            float64               `json:"salePrice"`
	OwnershipTitle       string                `json:"ownershipTitle"`
	PaymentPlan          *bool                 `json:"paymentPlan,omitempty"`
	YearBuilt            *int                  `json:"yearBuilt,omitempty"`
	YearRenovated        *int                  `json:"yearRenovated,omitempty"`
	AgencyFee            *float64              `json:"agencyFee,omitempty"`
	LegalFee             *float64              `json:"legalFee,omitempty"`
	SurveyFee            *float64              `json:"surveyFee,omitempty"`
	TitleProcessingFee   *float64              `json:"titleProcessingFee,omitempty"`
	DevelopmentFee       *float64              `json:"developmentFee,omitempty"`
	OtherFees            *float64              `json:"otherFees,omitempty"`
	ServiceCharge        *float64              `json:"serviceCharge,omitempty"`
	ServiceCharges       []*ServiceChargeInput `json:"serviceCharges,omitempty"`
	SaleTerms            *string               `json:"saleTerms,omitempty"`
	SaleAvailabilityFrom *time.Time            `json:"saleAvailabilityFrom,omitempty"`
}

type ScoredListing struct {
	Listing *domain.Listing `json:"listing"`
	Score   float64         `json:"score"`
	Ranking int             `json:"ranking"`
}

type ServiceChargeInput struct {
	Name   string               `json:"name"`
	Period domain.PaymentPeriod `json:"period"`
	Amount float64              `json:"amount"`
}

type ShortletDetailInput struct {
	NightlyRate          float64                  `json:"nightlyRate"`
	CautionFee           *float64                 `json:"cautionFee,omitempty"`
	CleaningFee          *float64                 `json:"cleaningFee,omitempty"`
	ServiceFee           *float64                 `json:"serviceFee,omitempty"`
	ExtraGuestFee        *float64                 `json:"extraGuestFee,omitempty"`
	MinNights            int                      `json:"minNights"`
	MaxNights            *int                     `json:"maxNights,omitempty"`
	MaxGuests            int                      `json:"maxGuests"`
	BaseGuestCount       *int                     `json:"baseGuestCount,omitempty"`
	CheckInTime          *string                  `json:"checkInTime,omitempty"`
	CheckOutTime         *string                  `json:"checkOutTime,omitempty"`
	AccommodationType    domain.AccommodationType `json:"accommodationType"`
	CalendarMonthsAhead  *int                     `json:"calendarMonthsAhead,omitempty"`
	AutoGenerateCalendar *bool                    `json:"autoGenerateCalendar,omitempty"`
	Rules                []*RuleGroupInput        `json:"rules,omitempty"`
	AmenitiesHighlights  []*AmenityHighlightInput `json:"amenitiesHighlights,omitempty"`
}

type TravelCompanionInput struct {
	Name         string  `json:"name"`
	AgeGroup     string  `json:"ageGroup"`
	Phone        *string `json:"phone,omitempty"`
	Relationship string  `json:"relationship"`
	PhotoURL     *string `json:"photoUrl,omitempty"`
}

type UpdateListingInput struct {
	Property        *UpdateListingPropertyInput `json:"property,omitempty"`
	Title           *string                     `json:"title,omitempty"`
	Description     *string                     `json:"description,omitempty"`
	Currency        *domain.CurrencyCode        `json:"currency,omitempty"`
	OwnerType       *domain.OwnerType           `json:"ownerType,omitempty"`
	HasCalendar     *bool                       `json:"hasCalendar,omitempty"`
	ShortletDetails *ShortletDetailInput        `json:"shortletDetails,omitempty"`
	RentalDetails   *RentalDetailInput          `json:"rentalDetails,omitempty"`
	SaleDetails     *SaleDetailInput            `json:"saleDetails,omitempty"`
}

type UpdateListingPropertyInput struct {
	UnitNumber         *string                   `json:"unitNumber,omitempty"`
	Address            *string                   `json:"address,omitempty"`
	City               *string                   `json:"city,omitempty"`
	State              *string                   `json:"state,omitempty"`
	PostalCode         *string                   `json:"postalCode,omitempty"`
	Country            *domain.CountryCode       `json:"country,omitempty"`
	Location           *LocationInput            `json:"location,omitempty"`
	PropertyClass      *domain.PropertyClass     `json:"propertyClass,omitempty"`
	PropertyType       *domain.PropertyType      `json:"propertyType,omitempty"`
	FurnishingType     *domain.FurnishingType    `json:"furnishingType,omitempty"`
	PropertyCondition  *domain.PropertyCondition `json:"propertyCondition,omitempty"`
	Bedrooms           *int                      `json:"bedrooms,omitempty"`
	Bathrooms          *int                      `json:"bathrooms,omitempty"`
	Toilets            *int                      `json:"toilets,omitempty"`
	HalfBathrooms      *int                      `json:"halfBathrooms,omitempty"`
	Floors             *int                      `json:"floors,omitempty"`
	Units              *int                      `json:"units,omitempty"`
	SquareMeters       *float64                  `json:"squareMeters,omitempty"`
	FloorArea          *float64                  `json:"floorArea,omitempty"`
	Amenities          []string                  `json:"amenities,omitempty"`
	FeaturesCommercial []string                  `json:"featuresCommercial,omitempty"`
}

type UpdateProfileInput struct {
	FullName                   *string                 `json:"fullName,omitempty"`
	BirthDate                  *time.Time              `json:"birthDate,omitempty"`
	PhoneNumbers               []string                `json:"phoneNumbers,omitempty"`
	Address                    *string                 `json:"address,omitempty"`
	City                       *string                 `json:"city,omitempty"`
	State                      *string                 `json:"state,omitempty"`
	Country                    *string                 `json:"country,omitempty"`
	ZipCode                    *string                 `json:"zipCode,omitempty"`
	Occupation                 *string                 `json:"occupation,omitempty"`
	Education                  *string                 `json:"education,omitempty"`
	Bio                        *string                 `json:"bio,omitempty"`
	Skills                     []string                `json:"skills,omitempty"`
	Languages                  []string                `json:"languages,omitempty"`
	Interests                  []string                `json:"interests,omitempty"`
	Hobbies                    []string                `json:"hobbies,omitempty"`
	FunFact                    *string                 `json:"funFact,omitempty"`
	ObsessedWith               *string                 `json:"obsessedWith,omitempty"`
	CommunityCommitment        *bool                   `json:"communityCommitment,omitempty"`
	BioVisible                 *bool                   `json:"bioVisible,omitempty"`
	AllowPersonalizedOffers    *bool                   `json:"allowPersonalizedOffers,omitempty"`
	EnablePerformanceAnalytics *bool                   `json:"enablePerformanceAnalytics,omitempty"`
	TravelCompanions           []*TravelCompanionInput `json:"travelCompanions,omitempty"`
}
