// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	domain1 "hauslet/internal/modules/discovery/domain"
	domain2 "hauslet/internal/modules/payments/domain"
	"hauslet/internal/modules/property/domain"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AmenityHighlightInput struct {
	Title   string `json:"title"`
	Summary string `json:"summary"`
	Icon    string `json:"icon"`
}

type CreateListingInput struct {
	OwnerType        domain.OwnerType            `json:"ownerType"`
	BusinessID       *uuid.UUID                  `json:"businessID,omitempty"`
	Property         *CreateListingPropertyInput `json:"property"`
	Title            string                      `json:"title"`
	Description      string                      `json:"description"`
	ExtraDescription *string                     `json:"extraDescription,omitempty"`
	Currency         *domain.CurrencyCode        `json:"currency,omitempty"`
	ListingType      domain.ListingType          `json:"listingType"`
	HasCalendar      *bool                       `json:"hasCalendar,omitempty"`
	ShortletDetails  *ShortletDetailInput        `json:"shortletDetails,omitempty"`
	RentalDetails    *RentalDetailInput          `json:"rentalDetails,omitempty"`
	SaleDetails      *SaleDetailInput            `json:"saleDetails,omitempty"`
}

type CreateListingPropertyInput struct {
	UnitNumber         *string                   `json:"unitNumber,omitempty"`
	Address            string                    `json:"address"`
	City               string                    `json:"city"`
	State              string                    `json:"state"`
	PostalCode         *string                   `json:"postalCode,omitempty"`
	Country            domain.CountryCode        `json:"country"`
	Location           *LocationInput            `json:"location,omitempty"`
	PropertyClass      domain.PropertyClass      `json:"propertyClass"`
	PropertyType       domain.PropertyType       `json:"propertyType"`
	FurnishingType     *domain.FurnishingType    `json:"furnishingType,omitempty"`
	PropertyCondition  *domain.PropertyCondition `json:"propertyCondition,omitempty"`
	Bedrooms           *int                      `json:"bedrooms,omitempty"`
	Bathrooms          *int                      `json:"bathrooms,omitempty"`
	Toilets            *int                      `json:"toilets,omitempty"`
	HalfBathrooms      *int                      `json:"halfBathrooms,omitempty"`
	Floors             *int                      `json:"floors,omitempty"`
	Units              *int                      `json:"units,omitempty"`
	SquareMeters       *float64                  `json:"squareMeters,omitempty"`
	FloorArea          *float64                  `json:"floorArea,omitempty"`
	Amenities          []*domain.AmenityGroup    `json:"amenities,omitempty"`
	FeaturesCommercial []*domain.AmenityGroup    `json:"featuresCommercial,omitempty"`
}

type DiscoverySearchFilterInput struct {
	Query         *string                `json:"query,omitempty"`
	Location      *LocationFilterInput   `json:"location,omitempty"`
	PriceRange    *PriceRangeFilterInput `json:"priceRange,omitempty"`
	PropertyTypes []domain.PropertyType  `json:"propertyTypes,omitempty"`
	Bedrooms      *IntRangeFilterInput   `json:"bedrooms,omitempty"`
	Bathrooms     *IntRangeFilterInput   `json:"bathrooms,omitempty"`
	ListingTypes  []domain.ListingType   `json:"listingTypes,omitempty"`
	City          *string                `json:"city,omitempty"`
	State         *string                `json:"state,omitempty"`
	Country       *string                `json:"country,omitempty"`
	Amenities     []string               `json:"amenities,omitempty"`
}

type FeedOptionsInput struct {
	Location          *LocationFilterInput      `json:"location,omitempty"`
	Limit             *int                      `json:"limit,omitempty"`
	SectionsToInclude []domain1.FeedSectionType `json:"sectionsToInclude,omitempty"`
}

type IntRangeFilterInput struct {
	Min *int `json:"min,omitempty"`
	Max *int `json:"max,omitempty"`
}

type ListingConnection struct {
	Edges      []*ListingEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type ListingEdge struct {
	Node   *domain.Listing `json:"node"`
	Cursor string          `json:"cursor"`
}

type ListingFilterInput struct {
	Query             *string                  `json:"query,omitempty"`
	OwnerID           *uuid.UUID               `json:"ownerId,omitempty"`
	PropertyID        *uuid.UUID               `json:"propertyId,omitempty"`
	OwnerTypes        []domain.OwnerType       `json:"ownerTypes,omitempty"`
	ListingTypes      []domain.ListingType     `json:"listingTypes,omitempty"`
	Statuses          []domain.ListingStatus   `json:"statuses,omitempty"`
	ReviewStatuses    []domain.ReviewStatus    `json:"reviewStatuses,omitempty"`
	HasCalendar       *bool                    `json:"hasCalendar,omitempty"`
	City              *string                  `json:"city,omitempty"`
	State             *string                  `json:"state,omitempty"`
	Country           *domain.CountryCode      `json:"country,omitempty"`
	Latitude          *float64                 `json:"latitude,omitempty"`
	Longitude         *float64                 `json:"longitude,omitempty"`
	RadiusMeters      *float64                 `json:"radiusMeters,omitempty"`
	PropertyTypes     []domain.PropertyType    `json:"propertyTypes,omitempty"`
	FurnishingTypes   []domain.FurnishingType  `json:"furnishingTypes,omitempty"`
	MinPrice          *float64                 `json:"minPrice,omitempty"`
	MaxPrice          *float64                 `json:"maxPrice,omitempty"`
	Currency          *domain.CurrencyCode     `json:"currency,omitempty"`
	MinBedrooms       *int                     `json:"minBedrooms,omitempty"`
	MaxBedrooms       *int                     `json:"maxBedrooms,omitempty"`
	MinBathrooms      *int                     `json:"minBathrooms,omitempty"`
	MaxBathrooms      *int                     `json:"maxBathrooms,omitempty"`
	ShortletFilter    *ShortletFilterInput     `json:"shortletFilter,omitempty"`
	RentalFilter      *RentalFilterInput       `json:"rentalFilter,omitempty"`
	SaleFilter        *SaleFilterInput         `json:"saleFilter,omitempty"`
	PropertyExtension *PropertyFilterExtension `json:"propertyExtension,omitempty"`
}

type ListingWithDistance struct {
	Listing        *domain.Listing `json:"listing"`
	DistanceMeters float64         `json:"distanceMeters"`
	Score          *float64        `json:"score,omitempty"`
}

type LocationFilterInput struct {
	Lat      float64 `json:"lat"`
	Lng      float64 `json:"lng"`
	RadiusKm float64 `json:"radiusKm"`
}

type LocationInput struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type MediaInput struct {
	Group        *string `json:"group,omitempty"`
	Caption      *string `json:"caption,omitempty"`
	IsPrimary    *bool   `json:"isPrimary,omitempty"`
	IsGroupCover *bool   `json:"isGroupCover,omitempty"`
	Order        *int    `json:"order,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PaymentInitResponse struct {
	Payment          *domain2.Payment `json:"payment"`
	AuthorizationURL *string          `json:"authorizationUrl,omitempty"`
	AccessCode       *string          `json:"accessCode,omitempty"`
}

type PlatformFeeBreakdown struct {
	GuestFeePercent         float64 `json:"guestFeePercent"`
	GuestFeeAmount          float64 `json:"guestFeeAmount"`
	HostCommissionPercent   float64 `json:"hostCommissionPercent"`
	HostCommissionAmount    float64 `json:"hostCommissionAmount"`
	PayoutProcessingPercent float64 `json:"payoutProcessingPercent"`
	PayoutProcessingAmount  float64 `json:"payoutProcessingAmount"`
	MinimumGuestFeeApplied  bool    `json:"minimumGuestFeeApplied"`
	HostNetAmount           float64 `json:"hostNetAmount"`
}

type PriceRangeFilterInput struct {
	Min      *int   `json:"min,omitempty"`
	Max      *int   `json:"max,omitempty"`
	Currency string `json:"currency"`
}

type PropertyFilterExtension struct {
	PropertyClasses    []domain.PropertyClass     `json:"propertyClasses,omitempty"`
	PropertyConditions []domain.PropertyCondition `json:"propertyConditions,omitempty"`
	Amenities          []string                   `json:"amenities,omitempty"`
}

type Query struct {
}

type RankingConfigInput struct {
	SemanticWeight  *float64 `json:"semanticWeight,omitempty"`
	PromotionWeight *float64 `json:"promotionWeight,omitempty"`
	RecencyWeight   *float64 `json:"recencyWeight,omitempty"`
	LocationWeight  *float64 `json:"locationWeight,omitempty"`
}

type RentalDetailInput struct {
	RentalPrice            float64                 `json:"rentalPrice"`
	RentalPricePeriod      domain.PaymentPeriod    `json:"rentalPricePeriod"`
	AgencyFee              *float64                `json:"agencyFee,omitempty"`
	LegalFee               *float64                `json:"legalFee,omitempty"`
	RegistrationFee        *float64                `json:"registrationFee,omitempty"`
	CautionFee             *float64                `json:"cautionFee,omitempty"`
	ServiceCharge          *float64                `json:"serviceCharge,omitempty"`
	ServiceCharges         []*domain.ServiceCharge `json:"serviceCharges,omitempty"`
	MinRentalPeriod        int                     `json:"minRentalPeriod"`
	MaxRentalPeriod        *int                    `json:"maxRentalPeriod,omitempty"`
	RentalAvailabilityFrom *time.Time              `json:"rentalAvailabilityFrom,omitempty"`
	RentalTerms            *string                 `json:"rentalTerms,omitempty"`
	RentalRules            []*domain.RuleGroup     `json:"rentalRules,omitempty"`
}

type RentalFilterInput struct {
	RentalPricePeriods []domain.PaymentPeriod `json:"rentalPricePeriods,omitempty"`
	MinRentalPeriodMin *int                   `json:"minRentalPeriodMin,omitempty"`
	MinRentalPeriodMax *int                   `json:"minRentalPeriodMax,omitempty"`
	MaxRentalPeriodMin *int                   `json:"maxRentalPeriodMin,omitempty"`
	MaxRentalPeriodMax *int                   `json:"maxRentalPeriodMax,omitempty"`
	AvailableFrom      *time.Time             `json:"availableFrom,omitempty"`
	AvailableTo        *time.Time             `json:"availableTo,omitempty"`
}

type SaleDetailInput struct {
	SalePrice            float64                 `json:"salePrice"`
	OwnershipTitle       string                  `json:"ownershipTitle"`
	PaymentPlan          *bool                   `json:"paymentPlan,omitempty"`
	YearBuilt            *int                    `json:"yearBuilt,omitempty"`
	YearRenovated        *int                    `json:"yearRenovated,omitempty"`
	AgencyFee            *float64                `json:"agencyFee,omitempty"`
	LegalFee             *float64                `json:"legalFee,omitempty"`
	SurveyFee            *float64                `json:"surveyFee,omitempty"`
	TitleProcessingFee   *float64                `json:"titleProcessingFee,omitempty"`
	DevelopmentFee       *float64                `json:"developmentFee,omitempty"`
	OtherFees            *float64                `json:"otherFees,omitempty"`
	ServiceCharge        *float64                `json:"serviceCharge,omitempty"`
	ServiceCharges       []*domain.ServiceCharge `json:"serviceCharges,omitempty"`
	SaleTerms            *string                 `json:"saleTerms,omitempty"`
	SaleAvailabilityFrom *time.Time              `json:"saleAvailabilityFrom,omitempty"`
}

type SaleFilterInput struct {
	OwnershipTitles []string `json:"ownershipTitles,omitempty"`
	PaymentPlan     *bool    `json:"paymentPlan,omitempty"`
}

type ScoredListing struct {
	Listing *domain.Listing `json:"listing"`
	Score   *float64        `json:"score,omitempty"`
	Ranking int             `json:"ranking"`
}

type SearchOptionsInput struct {
	Limit           *int                `json:"limit,omitempty"`
	IncludePromoted *bool               `json:"includePromoted,omitempty"`
	RankingConfig   *RankingConfigInput `json:"rankingConfig,omitempty"`
}

type ShortletDetailInput struct {
	NightlyRate          float64                  `json:"nightlyRate"`
	CautionFee           *float64                 `json:"cautionFee,omitempty"`
	CleaningFee          *float64                 `json:"cleaningFee,omitempty"`
	ServiceFee           *float64                 `json:"serviceFee,omitempty"`
	ExtraGuestFee        *float64                 `json:"extraGuestFee,omitempty"`
	MinNights            int                      `json:"minNights"`
	MaxNights            *int                     `json:"maxNights,omitempty"`
	MaxGuests            int                      `json:"maxGuests"`
	BaseGuestCount       *int                     `json:"baseGuestCount,omitempty"`
	CheckInTime          *string                  `json:"checkInTime,omitempty"`
	CheckOutTime         *string                  `json:"checkOutTime,omitempty"`
	AccommodationType    domain.AccommodationType `json:"accommodationType"`
	AutoAcceptBookings   *bool                    `json:"autoAcceptBookings,omitempty"`
	CalendarMonthsAhead  *int                     `json:"calendarMonthsAhead,omitempty"`
	AutoGenerateCalendar *bool                    `json:"autoGenerateCalendar,omitempty"`
	Rules                []*domain.RuleGroup      `json:"rules,omitempty"`
	AmenitiesHighlights  []*AmenityHighlightInput `json:"amenitiesHighlights,omitempty"`
}

type ShortletFilterInput struct {
	MinExtraGuestFee   *float64                   `json:"minExtraGuestFee,omitempty"`
	MaxExtraGuestFee   *float64                   `json:"maxExtraGuestFee,omitempty"`
	MinNightsMin       *int                       `json:"minNightsMin,omitempty"`
	MinNightsMax       *int                       `json:"minNightsMax,omitempty"`
	MaxNightsMin       *int                       `json:"maxNightsMin,omitempty"`
	MaxNightsMax       *int                       `json:"maxNightsMax,omitempty"`
	MinMaxGuests       *int                       `json:"minMaxGuests,omitempty"`
	BaseGuestCount     *int                       `json:"baseGuestCount,omitempty"`
	CheckInTimeAfter   *string                    `json:"checkInTimeAfter,omitempty"`
	CheckInTimeBefore  *string                    `json:"checkInTimeBefore,omitempty"`
	CheckOutTimeAfter  *string                    `json:"checkOutTimeAfter,omitempty"`
	CheckOutTimeBefore *string                    `json:"checkOutTimeBefore,omitempty"`
	AccommodationTypes []domain.AccommodationType `json:"accommodationTypes,omitempty"`
}

type ShowingAvailability struct {
	DayOfWeek DayOfWeek `json:"dayOfWeek"`
	StartTime string    `json:"startTime"`
	EndTime   string    `json:"endTime"`
	Timezone  *string   `json:"timezone,omitempty"`
}

type UpdateListingInput struct {
	Property         *UpdateListingPropertyInput `json:"property,omitempty"`
	Title            *string                     `json:"title,omitempty"`
	Description      *string                     `json:"description,omitempty"`
	ExtraDescription *string                     `json:"extraDescription,omitempty"`
	Currency         *domain.CurrencyCode        `json:"currency,omitempty"`
	OwnerType        *domain.OwnerType           `json:"ownerType,omitempty"`
	HasCalendar      *bool                       `json:"hasCalendar,omitempty"`
	ShortletDetails  *UpdateShortletDetailInput  `json:"shortletDetails,omitempty"`
	RentalDetails    *UpdateRentalDetailInput    `json:"rentalDetails,omitempty"`
	SaleDetails      *UpdateSaleDetailInput      `json:"saleDetails,omitempty"`
}

type UpdateListingPropertyInput struct {
	UnitNumber         *string                   `json:"unitNumber,omitempty"`
	Address            *string                   `json:"address,omitempty"`
	City               *string                   `json:"city,omitempty"`
	State              *string                   `json:"state,omitempty"`
	PostalCode         *string                   `json:"postalCode,omitempty"`
	Country            *domain.CountryCode       `json:"country,omitempty"`
	Location           *LocationInput            `json:"location,omitempty"`
	PropertyClass      *domain.PropertyClass     `json:"propertyClass,omitempty"`
	PropertyType       *domain.PropertyType      `json:"propertyType,omitempty"`
	FurnishingType     *domain.FurnishingType    `json:"furnishingType,omitempty"`
	PropertyCondition  *domain.PropertyCondition `json:"propertyCondition,omitempty"`
	Bedrooms           *int                      `json:"bedrooms,omitempty"`
	Bathrooms          *int                      `json:"bathrooms,omitempty"`
	Toilets            *int                      `json:"toilets,omitempty"`
	HalfBathrooms      *int                      `json:"halfBathrooms,omitempty"`
	Floors             *int                      `json:"floors,omitempty"`
	Units              *int                      `json:"units,omitempty"`
	SquareMeters       *float64                  `json:"squareMeters,omitempty"`
	FloorArea          *float64                  `json:"floorArea,omitempty"`
	Amenities          []*domain.AmenityGroup    `json:"amenities,omitempty"`
	FeaturesCommercial []*domain.AmenityGroup    `json:"featuresCommercial,omitempty"`
}

type UpdateRentalDetailInput struct {
	RentalPrice            *float64                `json:"rentalPrice,omitempty"`
	RentalPricePeriod      *domain.PaymentPeriod   `json:"rentalPricePeriod,omitempty"`
	AgencyFee              *float64                `json:"agencyFee,omitempty"`
	LegalFee               *float64                `json:"legalFee,omitempty"`
	RegistrationFee        *float64                `json:"registrationFee,omitempty"`
	CautionFee             *float64                `json:"cautionFee,omitempty"`
	ServiceCharge          *float64                `json:"serviceCharge,omitempty"`
	ServiceCharges         []*domain.ServiceCharge `json:"serviceCharges,omitempty"`
	MinRentalPeriod        *int                    `json:"minRentalPeriod,omitempty"`
	MaxRentalPeriod        *int                    `json:"maxRentalPeriod,omitempty"`
	RentalAvailabilityFrom *time.Time              `json:"rentalAvailabilityFrom,omitempty"`
	RentalTerms            *string                 `json:"rentalTerms,omitempty"`
	RentalRules            []*domain.RuleGroup     `json:"rentalRules,omitempty"`
}

type UpdateSaleDetailInput struct {
	SalePrice            *float64                `json:"salePrice,omitempty"`
	OwnershipTitle       *string                 `json:"ownershipTitle,omitempty"`
	PaymentPlan          *bool                   `json:"paymentPlan,omitempty"`
	YearBuilt            *int                    `json:"yearBuilt,omitempty"`
	YearRenovated        *int                    `json:"yearRenovated,omitempty"`
	AgencyFee            *float64                `json:"agencyFee,omitempty"`
	LegalFee             *float64                `json:"legalFee,omitempty"`
	SurveyFee            *float64                `json:"surveyFee,omitempty"`
	TitleProcessingFee   *float64                `json:"titleProcessingFee,omitempty"`
	DevelopmentFee       *float64                `json:"developmentFee,omitempty"`
	OtherFees            *float64                `json:"otherFees,omitempty"`
	ServiceCharge        *float64                `json:"serviceCharge,omitempty"`
	ServiceCharges       []*domain.ServiceCharge `json:"serviceCharges,omitempty"`
	SaleTerms            *string                 `json:"saleTerms,omitempty"`
	SaleAvailabilityFrom *time.Time              `json:"saleAvailabilityFrom,omitempty"`
}

type UpdateShortletDetailInput struct {
	NightlyRate          *float64                  `json:"nightlyRate,omitempty"`
	CautionFee           *float64                  `json:"cautionFee,omitempty"`
	CleaningFee          *float64                  `json:"cleaningFee,omitempty"`
	ServiceFee           *float64                  `json:"serviceFee,omitempty"`
	ExtraGuestFee        *float64                  `json:"extraGuestFee,omitempty"`
	MinNights            *int                      `json:"minNights,omitempty"`
	MaxNights            *int                      `json:"maxNights,omitempty"`
	MaxGuests            *int                      `json:"maxGuests,omitempty"`
	BaseGuestCount       *int                      `json:"baseGuestCount,omitempty"`
	CheckInTime          *string                   `json:"checkInTime,omitempty"`
	CheckOutTime         *string                   `json:"checkOutTime,omitempty"`
	AccommodationType    *domain.AccommodationType `json:"accommodationType,omitempty"`
	AutoAcceptBookings   *bool                     `json:"autoAcceptBookings,omitempty"`
	CalendarMonthsAhead  *int                      `json:"calendarMonthsAhead,omitempty"`
	AutoGenerateCalendar *bool                     `json:"autoGenerateCalendar,omitempty"`
	Rules                []*domain.RuleGroup       `json:"rules,omitempty"`
	AmenitiesHighlights  []*AmenityHighlightInput  `json:"amenitiesHighlights,omitempty"`
}

type UploadResult struct {
	UserID            string     `json:"userID"`
	Filename          string     `json:"filename"`
	UploadURL         string     `json:"uploadURL"`
	Key               string     `json:"key"`
	TravelCompanionID *uuid.UUID `json:"travelCompanionID,omitempty"`
}

type DayOfWeek string

const (
	DayOfWeekMonday    DayOfWeek = "monday"
	DayOfWeekTuesday   DayOfWeek = "tuesday"
	DayOfWeekWednesday DayOfWeek = "wednesday"
	DayOfWeekThursday  DayOfWeek = "thursday"
	DayOfWeekFriday    DayOfWeek = "friday"
	DayOfWeekSaturday  DayOfWeek = "saturday"
	DayOfWeekSunday    DayOfWeek = "sunday"
)

var AllDayOfWeek = []DayOfWeek{
	DayOfWeekMonday,
	DayOfWeekTuesday,
	DayOfWeekWednesday,
	DayOfWeekThursday,
	DayOfWeekFriday,
	DayOfWeekSaturday,
	DayOfWeekSunday,
}

func (e DayOfWeek) IsValid() bool {
	switch e {
	case DayOfWeekMonday, DayOfWeekTuesday, DayOfWeekWednesday, DayOfWeekThursday, DayOfWeekFriday, DayOfWeekSaturday, DayOfWeekSunday:
		return true
	}
	return false
}

func (e DayOfWeek) String() string {
	return string(e)
}

func (e *DayOfWeek) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DayOfWeek(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DayOfWeek", str)
	}
	return nil
}

func (e DayOfWeek) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DayOfWeek) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DayOfWeek) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReviewVisibility string

const (
	ReviewVisibilityHidden  ReviewVisibility = "hidden"
	ReviewVisibilityVisible ReviewVisibility = "visible"
)

var AllReviewVisibility = []ReviewVisibility{
	ReviewVisibilityHidden,
	ReviewVisibilityVisible,
}

func (e ReviewVisibility) IsValid() bool {
	switch e {
	case ReviewVisibilityHidden, ReviewVisibilityVisible:
		return true
	}
	return false
}

func (e ReviewVisibility) String() string {
	return string(e)
}

func (e *ReviewVisibility) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReviewVisibility(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReviewVisibility", str)
	}
	return nil
}

func (e ReviewVisibility) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReviewVisibility) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReviewVisibility) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
