// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Query struct {
}

type TravelCompanionInput struct {
	Name         string  `json:"name"`
	AgeGroup     string  `json:"ageGroup"`
	Phone        *string `json:"phone,omitempty"`
	Relationship string  `json:"relationship"`
	PhotoURL     *string `json:"photoUrl,omitempty"`
}

type UpdateProfileInput struct {
	FullName            *string                 `json:"fullName,omitempty"`
	BirthDate           *time.Time              `json:"birthDate,omitempty"`
	PhoneNumbers        []string                `json:"phoneNumbers,omitempty"`
	Address             *string                 `json:"address,omitempty"`
	City                *string                 `json:"city,omitempty"`
	State               *string                 `json:"state,omitempty"`
	Country             *string                 `json:"country,omitempty"`
	ZipCode             *string                 `json:"zipCode,omitempty"`
	Occupation          *string                 `json:"occupation,omitempty"`
	Education           *string                 `json:"education,omitempty"`
	Bio                 *string                 `json:"bio,omitempty"`
	Skills              []string                `json:"skills,omitempty"`
	Languages           []string                `json:"languages,omitempty"`
	Interests           []string                `json:"interests,omitempty"`
	Hobbies             []string                `json:"hobbies,omitempty"`
	FunFact             *string                 `json:"funFact,omitempty"`
	ObsessedWith        *string                 `json:"obsessedWith,omitempty"`
	CommunityCommitment *bool                   `json:"communityCommitment,omitempty"`
	TravelCompanions    []*TravelCompanionInput `json:"travelCompanions,omitempty"`
}
