package seeders

import (
	"fmt"
	"time"

	"hauslet/db/seeds/data"
	"hauslet/db/seeds/utils"
	propertySchema "hauslet/internal/modules/property/repository/schema"

	"github.com/google/uuid"
)

// SeedProperty seeds properties (physical assets)
func SeedProperty(ctx *SeedContext) error {
	// Get all users to assign as property owners
	var users []uuid.UUID
	if err := ctx.DB.Table("users").Select("id").Where("role = ?", "user").Scan(&users).Error; err != nil {
		return fmt.Errorf("failed to fetch users: %w", err)
	}

	if len(users) == 0 {
		return fmt.Errorf("no users found - seed auth module first")
	}

	for i := 0; i < ctx.Config.PropertyCount; i++ {
		if err := createRandomProperty(ctx, users); err != nil {
			return fmt.Errorf("failed to create property: %w", err)
		}
	}

	return nil
}

// createRandomProperty creates a single random property
func createRandomProperty(ctx *SeedContext, ownerIDs []uuid.UUID) error {
	// Pick random location
	location := data.GetRandomLocation()

	// Pick random property type
	propertyType := utils.RandomChoice(data.PropertyTypes)

	// Determine bedrooms based on property type
	bedroomOptions := data.BedroomDistribution[propertyType]
	bedrooms := utils.RandomChoice(bedroomOptions)
	bathrooms := bedrooms // Usually same or similar
	if bedrooms > 0 {
		bathrooms = utils.RandomInt(bedrooms, bedrooms+1)
	}
	toilets := bathrooms
	halfBathrooms := 0
	if utils.RandomBoolWithProbability(0.3) {
		halfBathrooms = utils.RandomInt(1, 2)
	}

	// Random owner
	ownerID := utils.RandomChoice(ownerIDs)

	// Generate property details
	property := propertySchema.Property{
		ID:       uuid.New(),
		PublicID: "", // Will be auto-generated by GORM hook

		// Location
		Address:    location.Address,
		City:       location.City,
		State:      location.State,
		PostalCode: location.PostCode,
		Country:    propertySchema.CountryNG,
		Location: &propertySchema.GeographyPoint{
			Lat: location.Latitude,
			Lng: location.Longitude,
		},

		// Classification
		PropertyClass:     "residential",
		PropertyType:      propertySchema.PropertyType(propertyType),
		FurnishingType:    propertySchema.FurnishingType(utils.RandomChoice(data.FurnishingTypes)),
		PropertyCondition: propertySchema.PropertyCondition(utils.RandomChoice(data.PropertyConditions)),

		// Details
		Bedrooms:      &bedrooms,
		Bathrooms:     &bathrooms,
		Toilets:       &toilets,
		HalfBathrooms: &halfBathrooms,
		Floors:        ptrInt(utils.RandomInt(1, 3)),
		Units:         1,

		OwnerID:      ownerID,
		SquareMeters: float64(utils.RandomInt(50, 500)),

		// Amenities
		Amenities: generateAmenities(),

		CreatedAt: utils.RandomPastDate(365),
		UpdatedAt: time.Now(),
	}

	return ctx.DB.Create(&property).Error
}

// generateAmenities creates a realistic set of amenities
func generateAmenities() []propertySchema.AmenitiesType {
	// Combine common + some optional amenities
	amenityCount := utils.RandomInt(2, 5)
	selected := utils.RandomUniqueChoices(data.OptionalAmenities, amenityCount)
	all := append(data.CommonAmenities, selected...)

	return []propertySchema.AmenitiesType{
		{
			Group: "general",
			Items: all,
		},
	}
}

// ptrInt returns a pointer to an int value
func ptrInt(v int) *int {
	return &v
}
