package oauth

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"github.com/go-pkgz/auth/v2/provider"
)

// PasswordlessSender adapts to the provider.Sender interface for hybrid passwordless login.
// It generates a 6-digit OTP code and builds a magic link, then sends both via email.
type PasswordlessSender struct {
	sendFn      SendPasswordlessEmailFunc
	generateOTP GenerateAndStoreOTPFunc
	baseURL     string
	ttlMinutes  int
}

// NewPasswordlessSender creates a Sender for the verified provider with hybrid support.
func NewPasswordlessSender(
	sendFn SendPasswordlessEmailFunc,
	generateOTP GenerateAndStoreOTPFunc,
	baseURL string,
	ttlMinutes int,
) provider.Sender {
	if ttlMinutes <= 0 {
		ttlMinutes = 10 // default 10 minutes
	}
	return &PasswordlessSender{
		sendFn:      sendFn,
		generateOTP: generateOTP,
		baseURL:     baseURL,
		ttlMinutes:  ttlMinutes,
	}
}

// Send implements provider.Sender.
// The text parameter contains the JWT token generated by go-pkgz/auth.
// We also generate a 6-digit OTP and send both options to the user.
func (s *PasswordlessSender) Send(address, jwtToken string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// Generate 6-digit OTP code and store in Redis
	otpCode, err := s.generateOTP(ctx, address)
	if err != nil {
		return fmt.Errorf("failed to generate OTP for passwordless login: %w", err)
	}

	// Build magic link URL with JWT token
	magicLink := s.buildMagicLink(jwtToken)

	// Send email with both options
	return s.sendFn(ctx, address, otpCode, magicLink, s.ttlMinutes)
}

// buildMagicLink constructs the magic link URL with the JWT token.
func (s *PasswordlessSender) buildMagicLink(jwtToken string) string {
	return fmt.Sprintf("%s/auth/email/login?token=%s", s.baseURL, url.QueryEscape(jwtToken))
}
