package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	domain2 "hauslet/internal/modules/auth/domain"
	domain3 "hauslet/internal/modules/business/domain"
	domain1 "hauslet/internal/modules/profile/domain"
	"hauslet/internal/modules/property/domain"
	domain4 "hauslet/internal/modules/wishlist/domain"
	"hauslet/internal/transport/graph/model"

	"github.com/google/uuid"
)

// Location is the resolver for the location field.
func (r *businessResolver) Location(ctx context.Context, obj *domain3.Business) (*domain.Location, error) {
	// Business.Location is already a *domain.Location, but it's from property domain
	// We need to return it as is since both Business and Property use the same Location type
	if obj.Location == nil {
		return nil, nil
	}
	return &domain.Location{
		Lat: obj.Location.Lat,
		Lng: obj.Location.Lng,
	}, nil
}

// Members is the resolver for the members field.
func (r *businessResolver) Members(ctx context.Context, obj *domain3.Business) ([]*domain3.BusinessMember, error) {
	members, err := r.BusinessResolver.BusinessMembers(ctx, obj.ID.String())
	if err != nil {
		return nil, err
	}
	result := make([]*domain3.BusinessMember, len(members))
	for i := range members {
		result[i] = &members[i]
	}
	return result, nil
}

// OwnerProfile is the resolver for the ownerProfile field.
func (r *listingResolver) OwnerProfile(ctx context.Context, obj *domain.Listing) (*domain1.Profile, error) {
	return r.PropertyResolver.OwnerProfile(ctx, obj)
}

// Property is the resolver for the property field.
func (r *listingResolver) Property(ctx context.Context, obj *domain.Listing) (*domain.Property, error) {
	return r.PropertyResolver.ListingProperty(ctx, obj)
}

// Thumbnails is the resolver for the thumbnails field.
func (r *listingMediaResolver) Thumbnails(ctx context.Context, obj *domain.ListingMedia) ([]*domain.ThumbnailVariant, error) {
	return r.PropertyResolver.ListingMediaThumbnails(ctx, obj)
}

// Ping is the resolver for the ping field.
func (r *mutationResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*domain1.Profile, error) {
	return r.ProfileResolver.UpdateProfile(ctx, input)
}

// AddTravelCompanion is the resolver for the addTravelCompanion field.
func (r *mutationResolver) AddTravelCompanion(ctx context.Context, userID string, input model.TravelCompanionInput) (bool, error) {
	return r.ProfileResolver.AddTravelCompanion(ctx, userID, input)
}

// UpdateTravelCompanion is the resolver for the updateTravelCompanion field.
func (r *mutationResolver) UpdateTravelCompanion(ctx context.Context, userID string, companionID string, input model.TravelCompanionInput) (bool, error) {
	return r.ProfileResolver.UpdateTravelCompanion(ctx, userID, companionID, input)
}

// DeleteTravelCompanion is the resolver for the deleteTravelCompanion field.
func (r *mutationResolver) DeleteTravelCompanion(ctx context.Context, userID string, companionID string) (bool, error) {
	return r.ProfileResolver.DeleteTravelCompanion(ctx, userID, companionID)
}

// DeleteProfile is the resolver for the deleteProfile field.
func (r *mutationResolver) DeleteProfile(ctx context.Context, userID string) (bool, error) {
	return r.ProfileResolver.DeleteProfile(ctx, userID)
}

// CreateListing is the resolver for the createListing field.
func (r *mutationResolver) CreateListing(ctx context.Context, input model.CreateListingInput) (*domain.Listing, error) {
	return r.PropertyResolver.CreateListing(ctx, input)
}

// UpdateListing is the resolver for the updateListing field.
func (r *mutationResolver) UpdateListing(ctx context.Context, id uuid.UUID, input model.UpdateListingInput) (*domain.Listing, error) {
	return r.PropertyResolver.UpdateListing(ctx, id, input)
}

// DeleteListing is the resolver for the deleteListing field.
func (r *mutationResolver) DeleteListing(ctx context.Context, id uuid.UUID, hard *bool) (bool, error) {
	return r.PropertyResolver.DeleteListing(ctx, id, hard)
}

// PublishListing is the resolver for the publishListing field.
func (r *mutationResolver) PublishListing(ctx context.Context, id uuid.UUID) (*domain.Listing, error) {
	return r.PropertyResolver.PublishListing(ctx, id)
}

// UnpublishListing is the resolver for the unpublishListing field.
func (r *mutationResolver) UnpublishListing(ctx context.Context, id uuid.UUID) (*domain.Listing, error) {
	return r.PropertyResolver.UnpublishListing(ctx, id)
}

// CreateBusiness is the resolver for the createBusiness field.
func (r *mutationResolver) CreateBusiness(ctx context.Context, input model.CreateBusinessInput) (*domain3.Business, error) {
	return r.BusinessResolver.CreateBusiness(ctx, input)
}

// UpdateBusiness is the resolver for the updateBusiness field.
func (r *mutationResolver) UpdateBusiness(ctx context.Context, id uuid.UUID, input model.UpdateBusinessInput) (*domain3.Business, error) {
	return r.BusinessResolver.UpdateBusiness(ctx, id.String(), input)
}

// DeleteBusiness is the resolver for the deleteBusiness field.
func (r *mutationResolver) DeleteBusiness(ctx context.Context, id uuid.UUID) (bool, error) {
	return r.BusinessResolver.DeleteBusiness(ctx, id.String())
}

// AddBusinessMember is the resolver for the addBusinessMember field.
func (r *mutationResolver) AddBusinessMember(ctx context.Context, businessID uuid.UUID, userID uuid.UUID, role domain3.MemberRole, customPermissions *model.MemberPermissionsInput) (*domain3.BusinessMember, error) {
	return r.BusinessResolver.AddBusinessMember(ctx, businessID.String(), userID.String(), role, customPermissions)
}

// UpdateMemberRole is the resolver for the updateMemberRole field.
func (r *mutationResolver) UpdateMemberRole(ctx context.Context, businessID uuid.UUID, memberID uuid.UUID, role domain3.MemberRole) (*domain3.BusinessMember, error) {
	return r.BusinessResolver.UpdateMemberRole(ctx, businessID.String(), memberID.String(), role)
}

// UpdateMemberPermissions is the resolver for the updateMemberPermissions field.
func (r *mutationResolver) UpdateMemberPermissions(ctx context.Context, businessID uuid.UUID, memberID uuid.UUID, permissions model.MemberPermissionsInput) (*domain3.BusinessMember, error) {
	return r.BusinessResolver.UpdateMemberPermissions(ctx, businessID.String(), memberID.String(), permissions)
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, businessID uuid.UUID, memberID uuid.UUID) (bool, error) {
	return r.BusinessResolver.RemoveMember(ctx, businessID.String(), memberID.String())
}

// InviteMember is the resolver for the inviteMember field.
func (r *mutationResolver) InviteMember(ctx context.Context, businessID uuid.UUID, input model.InviteMemberInput) (*domain3.BusinessInvitation, error) {
	return r.BusinessResolver.InviteMember(ctx, businessID.String(), input)
}

// AcceptInvitation is the resolver for the acceptInvitation field.
func (r *mutationResolver) AcceptInvitation(ctx context.Context, token string) (*domain3.BusinessMember, error) {
	return r.BusinessResolver.AcceptInvitation(ctx, token)
}

// DeclineInvitation is the resolver for the declineInvitation field.
func (r *mutationResolver) DeclineInvitation(ctx context.Context, token string) (bool, error) {
	return r.BusinessResolver.DeclineInvitation(ctx, token)
}

// RevokeInvitation is the resolver for the revokeInvitation field.
func (r *mutationResolver) RevokeInvitation(ctx context.Context, invitationID uuid.UUID) (bool, error) {
	return r.BusinessResolver.RevokeInvitation(ctx, invitationID.String())
}

// CreateWishlist is the resolver for the createWishlist field.
func (r *mutationResolver) CreateWishlist(ctx context.Context, input model.CreateWishlistInput) (*domain4.Wishlist, error) {
	return r.WishlistResolver.CreateWishlist(ctx, input)
}

// UpdateWishlist is the resolver for the updateWishlist field.
func (r *mutationResolver) UpdateWishlist(ctx context.Context, id uuid.UUID, input model.UpdateWishlistInput) (*domain4.Wishlist, error) {
	return r.WishlistResolver.UpdateWishlist(ctx, id, input)
}

// DeleteWishlist is the resolver for the deleteWishlist field.
func (r *mutationResolver) DeleteWishlist(ctx context.Context, id uuid.UUID) (bool, error) {
	return r.WishlistResolver.DeleteWishlist(ctx, id)
}

// AddWishlistItem is the resolver for the addWishlistItem field.
func (r *mutationResolver) AddWishlistItem(ctx context.Context, wishlistID uuid.UUID, listingID uuid.UUID, source *domain4.WishlistItemSource) (*domain4.WishlistItem, error) {
	return r.WishlistResolver.AddWishlistItem(ctx, wishlistID, listingID, source)
}

// RemoveWishlistItem is the resolver for the removeWishlistItem field.
func (r *mutationResolver) RemoveWishlistItem(ctx context.Context, wishlistID uuid.UUID, listingID uuid.UUID) (bool, error) {
	return r.WishlistResolver.RemoveWishlistItem(ctx, wishlistID, listingID)
}

// ImportWishlist is the resolver for the importWishlist field.
func (r *mutationResolver) ImportWishlist(ctx context.Context, sourceWishlistID uuid.UUID, newName *string) (*domain4.Wishlist, error) {
	return r.WishlistResolver.ImportWishlist(ctx, sourceWishlistID, newName)
}

// Gender is the resolver for the gender field.
func (r *profileResolver) Gender(ctx context.Context, obj *domain1.Profile) (*string, error) {
	if obj == nil {
		return nil, nil
	}
	if obj.Gender == "" {
		return nil, nil
	}
	g := string(obj.Gender)
	return &g, nil
}

// Amenities is the resolver for the amenities field.
func (r *propertyResolver) Amenities(ctx context.Context, obj *domain.Property) ([]*model.AmenityGroup, error) {
	if obj == nil || len(obj.Amenities) == 0 {
		return []*model.AmenityGroup{}, nil
	}

	// Convert domain.AmenityGroup to model.AmenityGroup
	result := make([]*model.AmenityGroup, len(obj.Amenities))
	for i, group := range obj.Amenities {
		result[i] = &model.AmenityGroup{
			Group: group.Group,
			Items: group.Items,
		}
	}
	return result, nil
}

// FeaturesCommercial is the resolver for the featuresCommercial field.
func (r *propertyResolver) FeaturesCommercial(ctx context.Context, obj *domain.Property) ([]*model.AmenityGroup, error) {
	if obj == nil || len(obj.FeaturesCommercial) == 0 {
		return []*model.AmenityGroup{}, nil
	}

	// Convert domain.AmenityGroup to model.AmenityGroup
	result := make([]*model.AmenityGroup, len(obj.FeaturesCommercial))
	for i, group := range obj.FeaturesCommercial {
		result[i] = &model.AmenityGroup{
			Group: group.Group,
			Items: group.Items,
		}
	}
	return result, nil
}

// Listings is the resolver for the listings field.
func (r *propertyResolver) Listings(ctx context.Context, obj *domain.Property, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.PropertyListings(ctx, obj, first, after)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*domain2.User, error) {
	return r.AuthResolver.Me(ctx)
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, id uuid.UUID) (*domain1.Profile, error) {
	return r.ProfileResolver.Profile(ctx, id)
}

// ProfileByUserID is the resolver for the profileByUserId field.
func (r *queryResolver) ProfileByUserID(ctx context.Context, userID string) (*domain1.Profile, error) {
	return r.ProfileResolver.ProfileByUserID(ctx, userID)
}

// Profiles is the resolver for the profiles field.
func (r *queryResolver) Profiles(ctx context.Context, limit *int, offset *int) ([]*domain1.Profile, error) {
	return r.ProfileResolver.Profiles(ctx, limit, offset)
}

// SearchProfiles is the resolver for the searchProfiles field.
func (r *queryResolver) SearchProfiles(ctx context.Context, query string, limit *int, offset *int) ([]*domain1.Profile, error) {
	return r.ProfileResolver.SearchProfiles(ctx, query, limit, offset)
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*domain1.Profile, error) {
	return r.ProfileResolver.MyProfile(ctx)
}

// UploadProfilePhoto is the resolver for the uploadProfilePhoto field.
func (r *queryResolver) UploadProfilePhoto(ctx context.Context, userID string, fileName string) (*model.UploadResult, error) {
	u, err := r.ProfileResolver.UploadProfilePhoto(ctx, userID, fileName)
	if err != nil {
		return nil, err
	}
	mdl := &model.UploadResult{
		UserID:    u.UserID,
		Filename:  u.Filename,
		UploadURL: u.URL,
		Key:       u.Key,
	}
	tc := u.TravelCompanionID
	if tc != uuid.Nil {
		mdl.TravelCompanionID = &tc
	}

	return mdl, nil
}

// UploadTravelCompanionPhoto is the resolver for the uploadTravelCompanionPhoto field.
func (r *queryResolver) UploadTravelCompanionPhoto(ctx context.Context, userID string, companionID string, fileName string) (*model.UploadResult, error) {
	companionUUID, err := uuid.Parse(companionID)
	if err != nil {
		return nil, fmt.Errorf("invalid companionID: %w", err)
	}
	u, err := r.ProfileResolver.UploadTravelCompanionPhoto(ctx, companionUUID, userID, fileName)
	if err != nil {
		return nil, err
	}
	mdl := &model.UploadResult{
		UserID:    u.UserID,
		Filename:  u.Filename,
		UploadURL: u.URL,
		Key:       u.Key,
	}
	tc := u.TravelCompanionID
	if tc != uuid.Nil {
		mdl.TravelCompanionID = &tc
	}

	return mdl, nil
}

// Listing is the resolver for the listing field.
func (r *queryResolver) Listing(ctx context.Context, id uuid.UUID) (*domain.Listing, error) {
	return r.PropertyResolver.Listing(ctx, id)
}

// ListingByPublicID is the resolver for the listingByPublicId field.
func (r *queryResolver) ListingByPublicID(ctx context.Context, publicID string) (*domain.Listing, error) {
	return r.PropertyResolver.ListingByPublicId(ctx, publicID)
}

// ListingBySlug is the resolver for the listingBySlug field.
func (r *queryResolver) ListingBySlug(ctx context.Context, slug string) (*domain.Listing, error) {
	return r.PropertyResolver.ListingBySlug(ctx, slug)
}

// Listings is the resolver for the listings field.
func (r *queryResolver) Listings(ctx context.Context, filter *model.ListingFilterInput, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.Listings(ctx, filter, first, after)
}

// ListingsByProperty is the resolver for the listingsByProperty field.
func (r *queryResolver) ListingsByProperty(ctx context.Context, propertyID uuid.UUID, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.ListingsByProperty(ctx, propertyID, first, after)
}

// MyListings is the resolver for the myListings field.
func (r *queryResolver) MyListings(ctx context.Context, filter *model.ListingFilterInput, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.MyListings(ctx, filter, first, after)
}

// ListingCompleteness is the resolver for the listingCompleteness field.
func (r *queryResolver) ListingCompleteness(ctx context.Context, listingID uuid.UUID) (*domain.ListingCompleteness, error) {
	return r.PropertyResolver.ListingCompleteness(ctx, listingID)
}

// BusinessListings is the resolver for the businessListings field.
func (r *queryResolver) BusinessListings(ctx context.Context, businessID uuid.UUID, filter *model.ListingFilterInput, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.BusinessListings(ctx, businessID, filter, first, after)
}

// MyIndividualListings is the resolver for the myIndividualListings field.
func (r *queryResolver) MyIndividualListings(ctx context.Context, filter *model.ListingFilterInput, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.MyIndividualListings(ctx, filter, first, after)
}

// ListingsNearPoint is the resolver for the listingsNearPoint field.
func (r *queryResolver) ListingsNearPoint(ctx context.Context, lat float64, lng float64, radiusMeters float64, filter *model.ListingFilterInput, limit *int) ([]*model.ListingWithDistance, error) {
	return r.PropertyResolver.ListingsNearPoint(ctx, lat, lng, radiusMeters, filter, limit)
}

// SearchListings is the resolver for the searchListings field.
func (r *queryResolver) SearchListings(ctx context.Context, filter *model.ListingFilterInput, limit *int) ([]*model.ScoredListing, error) {
	return r.PropertyResolver.SearchListings(ctx, filter, limit)
}

// SimilarListings is the resolver for the similarListings field.
func (r *queryResolver) SimilarListings(ctx context.Context, listingID uuid.UUID, limit *int, minSimilarity *float64) ([]*model.ScoredListing, error) {
	return r.PropertyResolver.SimilarListings(ctx, listingID, limit, minSimilarity)
}

// Business is the resolver for the business field.
func (r *queryResolver) Business(ctx context.Context, id uuid.UUID) (*domain3.Business, error) {
	return r.BusinessResolver.Business(ctx, id.String())
}

// BusinessBySlug is the resolver for the businessBySlug field.
func (r *queryResolver) BusinessBySlug(ctx context.Context, slug string) (*domain3.Business, error) {
	return r.BusinessResolver.BusinessBySlug(ctx, slug)
}

// AllBusinesses is the resolver for the allBusinesses field.
func (r *queryResolver) AllBusinesses(ctx context.Context, limit *int, offset *int) ([]*domain3.Business, error) {
	businesses, err := r.BusinessResolver.AllBusinesses(ctx, limit, offset)
	if err != nil {
		return nil, err
	}
	result := make([]*domain3.Business, len(businesses))
	for i := range businesses {
		result[i] = &businesses[i]
	}
	return result, nil
}

// SearchBusinesses is the resolver for the searchBusinesses field.
func (r *queryResolver) SearchBusinesses(ctx context.Context, query string, limit *int, offset *int) ([]*domain3.Business, error) {
	businesses, err := r.BusinessResolver.SearchBusinesses(ctx, query, limit, offset)
	if err != nil {
		return nil, err
	}
	result := make([]*domain3.Business, len(businesses))
	for i := range businesses {
		result[i] = &businesses[i]
	}
	return result, nil
}

// BusinessMembers is the resolver for the businessMembers field.
func (r *queryResolver) BusinessMembers(ctx context.Context, businessID uuid.UUID) ([]*domain3.BusinessMember, error) {
	members, err := r.BusinessResolver.BusinessMembers(ctx, businessID.String())
	if err != nil {
		return nil, err
	}
	result := make([]*domain3.BusinessMember, len(members))
	for i := range members {
		result[i] = &members[i]
	}
	return result, nil
}

// MyMemberships is the resolver for the myMemberships field.
func (r *queryResolver) MyMemberships(ctx context.Context) ([]*domain3.BusinessMember, error) {
	members, err := r.BusinessResolver.MyMemberships(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*domain3.BusinessMember, len(members))
	for i := range members {
		result[i] = &members[i]
	}
	return result, nil
}

// BusinessMember is the resolver for the businessMember field.
func (r *queryResolver) BusinessMember(ctx context.Context, businessID uuid.UUID, userID uuid.UUID) (*domain3.BusinessMember, error) {
	return r.BusinessResolver.BusinessMember(ctx, businessID.String(), userID.String())
}

// BusinessInvitations is the resolver for the businessInvitations field.
func (r *queryResolver) BusinessInvitations(ctx context.Context, businessID uuid.UUID) ([]*domain3.BusinessInvitation, error) {
	invitations, err := r.BusinessResolver.BusinessInvitations(ctx, businessID.String())
	if err != nil {
		return nil, err
	}
	result := make([]*domain3.BusinessInvitation, len(invitations))
	for i := range invitations {
		result[i] = &invitations[i]
	}
	return result, nil
}

// MyInvitations is the resolver for the myInvitations field.
func (r *queryResolver) MyInvitations(ctx context.Context, email string) ([]*domain3.BusinessInvitation, error) {
	invitations, err := r.BusinessResolver.MyInvitations(ctx, email)
	if err != nil {
		return nil, err
	}
	result := make([]*domain3.BusinessInvitation, len(invitations))
	for i := range invitations {
		result[i] = &invitations[i]
	}
	return result, nil
}

// MyBusinessPermissions is the resolver for the myBusinessPermissions field.
func (r *queryResolver) MyBusinessPermissions(ctx context.Context, businessID uuid.UUID) (*domain3.MemberPermissions, error) {
	return r.BusinessResolver.MyBusinessPermissions(ctx, businessID.String())
}

// Wishlist is the resolver for the wishlist field.
func (r *queryResolver) Wishlist(ctx context.Context, id uuid.UUID) (*domain4.Wishlist, error) {
	return r.WishlistResolver.Wishlist(ctx, id)
}

// MyWishlists is the resolver for the myWishlists field.
func (r *queryResolver) MyWishlists(ctx context.Context, limit *int, offset *int) ([]*domain4.Wishlist, error) {
	return r.WishlistResolver.MyWishlists(ctx, limit, offset)
}

// WishlistItems is the resolver for the wishlistItems field.
func (r *queryResolver) WishlistItems(ctx context.Context, wishlistID uuid.UUID, limit *int, offset *int) ([]*domain4.WishlistItem, error) {
	return r.WishlistResolver.WishlistItems(ctx, wishlistID, limit, offset)
}

// IsListingInWishlist is the resolver for the isListingInWishlist field.
func (r *queryResolver) IsListingInWishlist(ctx context.Context, wishlistID uuid.UUID, listingID uuid.UUID) (bool, error) {
	return r.WishlistResolver.IsListingInWishlist(ctx, wishlistID, listingID)
}

// ServiceCharges is the resolver for the serviceCharges field.
func (r *rentalDetailResolver) ServiceCharges(ctx context.Context, obj *domain.RentalDetail) ([]*domain.ServiceCharge, error) {
	if obj == nil || obj.ServiceChargeBreakdown == nil {
		return []*domain.ServiceCharge{}, nil
	}

	charges := make([]*domain.ServiceCharge, len(*obj.ServiceChargeBreakdown))
	for i, charge := range *obj.ServiceChargeBreakdown {
		c := charge
		charges[i] = &c
	}
	return charges, nil
}

// Rules is the resolver for the rules field.
func (r *ruleGroupResolver) Rules(ctx context.Context, obj *domain.RuleGroup) ([]*model.RuleItem, error) {
	if obj == nil || len(obj.Rules) == 0 {
		return []*model.RuleItem{}, nil
	}

	// Convert domain.RuleItem to model.RuleItem
	rules := make([]*model.RuleItem, len(obj.Rules))
	for i, item := range obj.Rules {
		rules[i] = &model.RuleItem{
			Name:        model.RuleSubCategory(item.Name),
			Description: item.Description,
		}
	}
	return rules, nil
}

// ServiceCharges is the resolver for the serviceCharges field.
func (r *saleDetailResolver) ServiceCharges(ctx context.Context, obj *domain.SaleDetail) ([]*domain.ServiceCharge, error) {
	if obj == nil || obj.ServiceChargeBreakdown == nil {
		return []*domain.ServiceCharge{}, nil
	}

	charges := make([]*domain.ServiceCharge, len(*obj.ServiceChargeBreakdown))
	for i, charge := range *obj.ServiceChargeBreakdown {
		c := charge
		charges[i] = &c
	}
	return charges, nil
}

// AgeGroup is the resolver for the ageGroup field.
func (r *travelCompanionResolver) AgeGroup(ctx context.Context, obj *domain1.TravelCompanion) (string, error) {
	if obj == nil {
		return "", nil
	}
	return string(obj.AgeGroup), nil
}

// Relationship is the resolver for the relationship field.
func (r *travelCompanionResolver) Relationship(ctx context.Context, obj *domain1.TravelCompanion) (string, error) {
	if obj == nil {
		return "", nil
	}
	return string(obj.Relationship), nil
}

// ItemCount is the resolver for the itemCount field.
func (r *wishlistResolver) ItemCount(ctx context.Context, obj *domain4.Wishlist) (int, error) {
	return r.WishlistResolver.WishlistItemCount(ctx, obj)
}

// Items is the resolver for the items field.
func (r *wishlistResolver) Items(ctx context.Context, obj *domain4.Wishlist, limit *int, offset *int) ([]*domain4.WishlistItem, error) {
	return r.WishlistResolver.WishlistItems(ctx, obj.ID, limit, offset)
}

// Listing is the resolver for the listing field.
func (r *wishlistItemResolver) Listing(ctx context.Context, obj *domain4.WishlistItem) (*domain.Listing, error) {
	return r.WishlistResolver.WishlistItemListing(ctx, obj)
}

// Business returns BusinessResolver implementation.
func (r *Resolver) Business() BusinessResolver { return &businessResolver{r} }

// Listing returns ListingResolver implementation.
func (r *Resolver) Listing() ListingResolver { return &listingResolver{r} }

// ListingMedia returns ListingMediaResolver implementation.
func (r *Resolver) ListingMedia() ListingMediaResolver { return &listingMediaResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Profile returns ProfileResolver implementation.
func (r *Resolver) Profile() ProfileResolver { return &profileResolver{r} }

// Property returns PropertyResolver implementation.
func (r *Resolver) Property() PropertyResolver { return &propertyResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// RentalDetail returns RentalDetailResolver implementation.
func (r *Resolver) RentalDetail() RentalDetailResolver { return &rentalDetailResolver{r} }

// RuleGroup returns RuleGroupResolver implementation.
func (r *Resolver) RuleGroup() RuleGroupResolver { return &ruleGroupResolver{r} }

// SaleDetail returns SaleDetailResolver implementation.
func (r *Resolver) SaleDetail() SaleDetailResolver { return &saleDetailResolver{r} }

// TravelCompanion returns TravelCompanionResolver implementation.
func (r *Resolver) TravelCompanion() TravelCompanionResolver { return &travelCompanionResolver{r} }

// Wishlist returns WishlistResolver implementation.
func (r *Resolver) Wishlist() WishlistResolver { return &wishlistResolver{r} }

// WishlistItem returns WishlistItemResolver implementation.
func (r *Resolver) WishlistItem() WishlistItemResolver { return &wishlistItemResolver{r} }

type businessResolver struct{ *Resolver }
type listingResolver struct{ *Resolver }
type listingMediaResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type profileResolver struct{ *Resolver }
type propertyResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type rentalDetailResolver struct{ *Resolver }
type ruleGroupResolver struct{ *Resolver }
type saleDetailResolver struct{ *Resolver }
type travelCompanionResolver struct{ *Resolver }
type wishlistResolver struct{ *Resolver }
type wishlistItemResolver struct{ *Resolver }
