package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	domain2 "hauslet/internal/modules/auth/domain"
	domain1 "hauslet/internal/modules/profile/domain"
	"hauslet/internal/modules/property/domain"
	"hauslet/internal/transport/graph/model"

	"github.com/google/uuid"
)

// Property is the resolver for the property field.
func (r *listingResolver) Property(ctx context.Context, obj *domain.Listing) (*domain.Property, error) {
	return r.PropertyResolver.ListingProperty(ctx, obj)
}

// Thumbnails is the resolver for the thumbnails field.
func (r *listingMediaResolver) Thumbnails(ctx context.Context, obj *domain.ListingMedia) ([]*domain.ThumbnailVariant, error) {
	return r.PropertyResolver.ListingMediaThumbnails(ctx, obj)
}

// Ping is the resolver for the ping field.
func (r *mutationResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*domain1.Profile, error) {
	return r.ProfileResolver.UpdateProfile(ctx, input)
}

// AddTravelCompanion is the resolver for the addTravelCompanion field.
func (r *mutationResolver) AddTravelCompanion(ctx context.Context, userID string, input model.TravelCompanionInput) (bool, error) {
	return r.ProfileResolver.AddTravelCompanion(ctx, userID, input)
}

// UpdateTravelCompanion is the resolver for the updateTravelCompanion field.
func (r *mutationResolver) UpdateTravelCompanion(ctx context.Context, userID string, companionID string, input model.TravelCompanionInput) (bool, error) {
	return r.ProfileResolver.UpdateTravelCompanion(ctx, userID, companionID, input)
}

// DeleteTravelCompanion is the resolver for the deleteTravelCompanion field.
func (r *mutationResolver) DeleteTravelCompanion(ctx context.Context, userID string, companionID string) (bool, error) {
	return r.ProfileResolver.DeleteTravelCompanion(ctx, userID, companionID)
}

// DeleteProfile is the resolver for the deleteProfile field.
func (r *mutationResolver) DeleteProfile(ctx context.Context, userID string) (bool, error) {
	return r.ProfileResolver.DeleteProfile(ctx, userID)
}

// CreateListing is the resolver for the createListing field.
func (r *mutationResolver) CreateListing(ctx context.Context, input model.CreateListingInput) (*domain.Listing, error) {
	return r.PropertyResolver.CreateListing(ctx, input)
}

// UpdateListing is the resolver for the updateListing field.
func (r *mutationResolver) UpdateListing(ctx context.Context, id uuid.UUID, input model.UpdateListingInput) (*domain.Listing, error) {
	return r.PropertyResolver.UpdateListing(ctx, id, input)
}

// DeleteListing is the resolver for the deleteListing field.
func (r *mutationResolver) DeleteListing(ctx context.Context, id uuid.UUID, hard *bool) (bool, error) {
	return r.PropertyResolver.DeleteListing(ctx, id, hard)
}

// PublishListing is the resolver for the publishListing field.
func (r *mutationResolver) PublishListing(ctx context.Context, id uuid.UUID) (*domain.Listing, error) {
	return r.PropertyResolver.PublishListing(ctx, id)
}

// UnpublishListing is the resolver for the unpublishListing field.
func (r *mutationResolver) UnpublishListing(ctx context.Context, id uuid.UUID) (*domain.Listing, error) {
	return r.PropertyResolver.UnpublishListing(ctx, id)
}

// Gender is the resolver for the gender field.
func (r *profileResolver) Gender(ctx context.Context, obj *domain1.Profile) (*string, error) {
	panic(fmt.Errorf("not implemented: Gender - gender"))
}

// Property field resolvers.
func (r *propertyResolver) Listings(ctx context.Context, obj *domain.Property, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.PropertyListings(ctx, obj, first, after)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*domain2.User, error) {
	return r.AuthResolver.Me(ctx)
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, id uuid.UUID) (*domain1.Profile, error) {
	return r.ProfileResolver.Profile(ctx, id)
}

// ProfileByUserID is the resolver for the profileByUserId field.
func (r *queryResolver) ProfileByUserID(ctx context.Context, userID string) (*domain1.Profile, error) {
	return r.ProfileResolver.ProfileByUserID(ctx, userID)
}

// Profiles is the resolver for the profiles field.
func (r *queryResolver) Profiles(ctx context.Context, limit *int, offset *int) ([]*domain1.Profile, error) {
	return r.ProfileResolver.Profiles(ctx, limit, offset)
}

// SearchProfiles is the resolver for the searchProfiles field.
func (r *queryResolver) SearchProfiles(ctx context.Context, query string, limit *int, offset *int) ([]*domain1.Profile, error) {
	return r.ProfileResolver.SearchProfiles(ctx, query, limit, offset)
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*domain1.Profile, error) {
	return r.ProfileResolver.MyProfile(ctx)
}

// UploadProfilePhoto is the resolver for the uploadProfilePhoto field.
func (r *queryResolver) UploadProfilePhoto(ctx context.Context, userID string, fileName string) (*model.UploadResult, error) {
	uploadResult, err := r.ProfileResolver.UploadProfilePhoto(ctx, userID, fileName)
	if err != nil {
		return nil, err
	}
	return &model.UploadResult{
		UserID:    uploadResult.UserID,
		Filename:  uploadResult.Filename,
		UploadURL: uploadResult.URL,
		Key:       uploadResult.Key,
	}, nil
}

// UploadTravelCompanionPhoto is the resolver for the uploadTravelCompanionPhoto field.
func (r *queryResolver) UploadTravelCompanionPhoto(ctx context.Context, userID string, companionID string, fileName string) (*model.UploadResult, error) {
	companionIDUUID, err := uuid.Parse(companionID)
	if err != nil {
		return nil, err
	}
	uploadResult, err := r.ProfileResolver.UploadTravelCompanionPhoto(ctx, companionIDUUID, userID, fileName)
	if err != nil {
		return nil, err
	}
	return &model.UploadResult{
		UserID:    uploadResult.UserID,
		Filename:  uploadResult.Filename,
		UploadURL: uploadResult.URL,
		Key:       uploadResult.Key,
	}, nil
}

// Listing is the resolver for the listing field.
func (r *queryResolver) Listing(ctx context.Context, id uuid.UUID) (*domain.Listing, error) {
	return r.PropertyResolver.Listing(ctx, id)
}

// ListingByPublicID is the resolver for the listingByPublicId field.
func (r *queryResolver) ListingByPublicID(ctx context.Context, publicID string) (*domain.Listing, error) {
	panic(fmt.Errorf("not implemented: ListingByPublicID - listingByPublicId"))
}

// ListingBySlug is the resolver for the listingBySlug field.
func (r *queryResolver) ListingBySlug(ctx context.Context, slug string) (*domain.Listing, error) {
	return r.PropertyResolver.ListingBySlug(ctx, slug)
}

// Listings is the resolver for the listings field.
func (r *queryResolver) Listings(ctx context.Context, filter *model.ListingFilterInput, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.Listings(ctx, filter, first, after)
}

// ListingsByProperty is the resolver for the listingsByProperty field.
func (r *queryResolver) ListingsByProperty(ctx context.Context, propertyID uuid.UUID, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.ListingsByProperty(ctx, propertyID, first, after)
}

// MyListings is the resolver for the myListings field.
func (r *queryResolver) MyListings(ctx context.Context, filter *model.ListingFilterInput, first *int, after *string) (*model.ListingConnection, error) {
	return r.PropertyResolver.MyListings(ctx, filter, first, after)
}

// ListingCompleteness is the resolver for the listingCompleteness field.
func (r *queryResolver) ListingCompleteness(ctx context.Context, listingID uuid.UUID) (*domain.ListingCompleteness, error) {
	return r.PropertyResolver.ListingCompleteness(ctx, listingID)
}

// ListingsNearPoint is the resolver for the listingsNearPoint field.
func (r *queryResolver) ListingsNearPoint(ctx context.Context, lat float64, lng float64, radiusMeters float64, filter *model.ListingFilterInput, limit *int) ([]*model.ListingWithDistance, error) {
	return r.PropertyResolver.ListingsNearPoint(ctx, lat, lng, radiusMeters, filter, limit)
}

// SearchListings is the resolver for the searchListings field.
func (r *queryResolver) SearchListings(ctx context.Context, query string, filter *model.ListingFilterInput, limit *int) ([]*model.ScoredListing, error) {
	return r.PropertyResolver.SearchListings(ctx, query, filter, limit)
}

// SimilarListings is the resolver for the similarListings field.
func (r *queryResolver) SimilarListings(ctx context.Context, listingID uuid.UUID, limit *int, minSimilarity *float64) ([]*model.ScoredListing, error) {
	return r.PropertyResolver.SimilarListings(ctx, listingID, limit, minSimilarity)
}

// Detail field resolvers.
func (r *rentalDetailResolver) ServiceCharges(ctx context.Context, obj *domain.RentalDetail) ([]*domain.ServiceCharge, error) {
	return r.PropertyResolver.RentalDetailServiceCharges(ctx, obj)
}

// ServiceCharges is the resolver for the serviceCharges field.
func (r *saleDetailResolver) ServiceCharges(ctx context.Context, obj *domain.SaleDetail) ([]*domain.ServiceCharge, error) {
	return r.PropertyResolver.SaleDetailServiceCharges(ctx, obj)
}

// AgeGroup is the resolver for the ageGroup field.
func (r *travelCompanionResolver) AgeGroup(ctx context.Context, obj *domain1.TravelCompanion) (string, error) {
	return string(obj.AgeGroup), nil
}

// Relationship is the resolver for the relationship field.
func (r *travelCompanionResolver) Relationship(ctx context.Context, obj *domain1.TravelCompanion) (string, error) {
	return string(obj.Relationship), nil
}

// Listing returns ListingResolver implementation.
func (r *Resolver) Listing() ListingResolver { return &listingResolver{r} }

// ListingMedia returns ListingMediaResolver implementation.
func (r *Resolver) ListingMedia() ListingMediaResolver { return &listingMediaResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Profile returns ProfileResolver implementation.
func (r *Resolver) Profile() ProfileResolver { return &profileResolver{r} }

// Property returns PropertyResolver implementation.
func (r *Resolver) Property() PropertyResolver { return &propertyResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// RentalDetail returns RentalDetailResolver implementation.
func (r *Resolver) RentalDetail() RentalDetailResolver { return &rentalDetailResolver{r} }

// SaleDetail returns SaleDetailResolver implementation.
func (r *Resolver) SaleDetail() SaleDetailResolver { return &saleDetailResolver{r} }

// TravelCompanion returns TravelCompanionResolver implementation.
func (r *Resolver) TravelCompanion() TravelCompanionResolver { return &travelCompanionResolver{r} }

type listingResolver struct{ *Resolver }
type listingMediaResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type profileResolver struct{ *Resolver }
type propertyResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type rentalDetailResolver struct{ *Resolver }
type saleDetailResolver struct{ *Resolver }
type travelCompanionResolver struct{ *Resolver }
