package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"hauslet/internal/graph/loaders"
	"hauslet/internal/graph/model"
	"hauslet/internal/profile/domain"

	"github.com/google/uuid"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*domain.Profile, error) {
	viewer := viewerFromContext(ctx)
	if viewer == nil || viewer.UserID == "" {
		return nil, fmt.Errorf("unauthenticated")
	}

	// Load current profile for the authenticated user
	profile, err := r.ProfileService.GetProfileByUserID(ctx, viewer.UserID)
	if err != nil {
		return nil, err
	}
	if profile == nil {
		return nil, fmt.Errorf("profile not found")
	}

	updates := make(map[string]interface{})
	if input.FullName != nil {
		updates["full_name"] = input.FullName
	}
	if input.BirthDate != nil {
		updates["birth_date"] = input.BirthDate
	}
	if input.PhoneNumbers != nil {
		updates["phone_numbers"] = input.PhoneNumbers
	}
	if input.Address != nil {
		updates["address"] = input.Address
	}
	if input.City != nil {
		updates["city"] = input.City
	}
	if input.State != nil {
		updates["state"] = input.State
	}
	if input.Country != nil {
		updates["country"] = input.Country
	}
	if input.ZipCode != nil {
		updates["zip_code"] = input.ZipCode
	}
	if input.Occupation != nil {
		updates["occupation"] = input.Occupation
	}
	if input.Education != nil {
		updates["education"] = input.Education
	}
	if input.Bio != nil {
		updates["bio"] = input.Bio
	}
	if input.Skills != nil {
		updates["skills"] = input.Skills
	}
	if input.Languages != nil {
		updates["languages"] = input.Languages
	}
	if input.Interests != nil {
		updates["interests"] = input.Interests
	}
	if input.Hobbies != nil {
		updates["hobbies"] = input.Hobbies
	}
	if input.FunFact != nil {
		updates["fun_fact"] = input.FunFact
	}
	if input.ObsessedWith != nil {
		updates["obsessed_with"] = input.ObsessedWith
	}
	if input.CommunityCommitment != nil {
		updates["community_commitment"] = *input.CommunityCommitment
	}

	companionsProvided := input.TravelCompanions != nil
	var companions []domain.TravelCompanion
	if companionsProvided {
		companions = make([]domain.TravelCompanion, 0, len(input.TravelCompanions))
		for _, tc := range input.TravelCompanions {
			if tc == nil {
				continue
			}
			companions = append(companions, domain.TravelCompanion{
				Name:         tc.Name,
				AgeGroup:     tc.AgeGroup,
				Phone:        tc.Phone,
				Relationship: tc.Relationship,
				PhotoURL:     tc.PhotoURL,
			})
		}
	}

	updated := profile
	if len(updates) > 0 {
		updated, err = r.ProfileService.PatchProfile(ctx, profile.ID.String(), updates)
		if err != nil {
			return nil, err
		}
	}

	if companionsProvided {
		if err := r.ProfileService.UpdateTravelCompanions(ctx, viewer.UserID, companions); err != nil {
			return nil, err
		}
		if updated != nil {
			updated.TravelCompanions = companions
		}
	}

	return sanitizeProfileForViewer(updated, viewer), nil
}

// AddBadge is the resolver for the addBadge field.
func (r *mutationResolver) AddBadge(ctx context.Context, userID string, badge domain.Badge) (*domain.Profile, error) {
	if err := ensureMutationAllowed(ctx, userID); err != nil {
		return nil, err
	}

	if err := r.ProfileService.AddBadge(ctx, userID, badge); err != nil {
		return nil, err
	}

	profile, err := r.ProfileService.GetProfileByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}

	return sanitizeProfileForViewer(profile, viewerFromContext(ctx)), nil
}

// RemoveBadge is the resolver for the removeBadge field.
func (r *mutationResolver) RemoveBadge(ctx context.Context, userID string, badge domain.Badge) (*domain.Profile, error) {
	if err := ensureMutationAllowed(ctx, userID); err != nil {
		return nil, err
	}

	if err := r.ProfileService.RemoveBadge(ctx, userID, badge); err != nil {
		return nil, err
	}

	profile, err := r.ProfileService.GetProfileByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}

	return sanitizeProfileForViewer(profile, viewerFromContext(ctx)), nil
}

// Badges resolves the detailed badge objects for a profile.
func (r *profileResolver) Badges(ctx context.Context, obj *domain.Profile) ([]*domain.BadgeDetails, error) {
	badges := make([]*domain.BadgeDetails, 0, len(obj.Badges))
	for _, b := range obj.Badges {
		details := domain.GetBadgeDetails(b)
		badge := details // copy to avoid pointer reuse in loop
		badges = append(badges, &badge)
	}
	return badges, nil
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, id uuid.UUID) (*domain.Profile, error) {
	p, err := r.ProfileService.GetProfileByID(ctx, id.String())
	if err != nil {
		return nil, err
	}
	return sanitizeProfileForViewer(p, viewerFromContext(ctx)), nil
}

// ProfileByUserID is the resolver for the profileByUserId field.
func (r *queryResolver) ProfileByUserID(ctx context.Context, userID string) (*domain.Profile, error) {
	if l := loaders.For(ctx); l != nil && l.Profile != nil {
		if p, err := l.Profile.Load(ctx, userID); err == nil {
			return sanitizeProfileForViewer(p, viewerFromContext(ctx)), nil
		}
	}

	p, err := r.ProfileService.GetProfileByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return sanitizeProfileForViewer(p, viewerFromContext(ctx)), nil
}

// Profiles is the resolver for the profiles field.
func (r *queryResolver) Profiles(ctx context.Context, limit *int, offset *int) ([]*domain.Profile, error) {
	l := 20
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	profiles, err := r.ProfileService.ListProfiles(ctx, l, o)
	if err != nil {
		return nil, err
	}
	return sanitizeProfilesForViewer(profiles, viewerFromContext(ctx)), nil
}

// SearchProfiles is the resolver for the searchProfiles field.
func (r *queryResolver) SearchProfiles(ctx context.Context, query string, limit *int, offset *int) ([]*domain.Profile, error) {
	l := 20
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	profiles, err := r.ProfileService.SearchProfiles(ctx, query, l, o)
	if err != nil {
		return nil, err
	}
	return sanitizeProfilesForViewer(profiles, viewerFromContext(ctx)), nil
}

// ProfilesByUserType is the resolver for the profilesByUserType field.
func (r *queryResolver) ProfilesByUserType(ctx context.Context, userType domain.UserType, limit *int, offset *int) ([]*domain.Profile, error) {
	l := 20
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	profiles, err := r.ProfileService.GetProfilesByUserType(ctx, string(userType), l, o)
	if err != nil {
		return nil, err
	}
	return sanitizeProfilesForViewer(profiles, viewerFromContext(ctx)), nil
}

// VerifiedProfiles is the resolver for the verifiedProfiles field.
func (r *queryResolver) VerifiedProfiles(ctx context.Context, level *string, limit *int, offset *int) ([]*domain.Profile, error) {
	l := 20
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	levelVal := ""
	if level != nil {
		levelVal = *level
	}

	profiles, err := r.ProfileService.GetVerifiedProfiles(ctx, levelVal, l, o)
	if err != nil {
		return nil, err
	}
	return sanitizeProfilesForViewer(profiles, viewerFromContext(ctx)), nil
}

// Profile returns ProfileResolver implementation.
func (r *Resolver) Profile() ProfileResolver { return &profileResolver{r} }

type profileResolver struct{ *Resolver }
